# Generated by Django 5.2.15 on 2026-06-19 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rows_count', models.IntegerField(default=0)),
                ('columns_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='uploaded', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('missing_values', models.IntegerField(default=0)),
                ('duplicate_rows', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('dataset', models.CharField(max_length=255)),
                ('generated', models.CharField(default='Just now', max_length=100)),
                ('visuals_count', models.IntegerField(default=3)),
                ('dax_count', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_id', models.CharField(max_length=100)),
                ('column', models.CharField(max_length=255)),
                ('issue', models.CharField(max_length=255)),
                ('recommendation', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=100)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('unique_values', models.IntegerField(default=0)),
                ('missing_count', models.IntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='api.dataset')),
            ],
        ),
    ]
