# Generated by Django 5.2.15 on 2026-06-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dax_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='visuals_data',
            field=models.JSONField(default=list),
        ),
    ]
