# Generated by Django 5.2.15 on 2026-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_type",
            field=models.CharField(default="bi", max_length=50),
        ),
    ]
