# Generated by Django 5.2.15 on 2026-07-08 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_report_is_public_report_share_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_id", models.CharField(max_length=255)),
                ("layout", models.CharField(default="grid-2x2", max_length=50)),
                ("theme_style", models.CharField(default="default", max_length=50)),
                ("theme_font", models.CharField(default="sans", max_length=50)),
                ("charts", models.JSONField(default=list)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "share_token",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
